name: Python CI pipeline

on:
  push:
    branches: ["main"]
  
  pull_request:
    branches: ["main"]

env:
  global_variable: "hello "
  

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      job_variable: "World"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run:  |
          pip install -r requirements.txt
      
      - name: Run tests
        run:  |
          pytest

      - name: Accessing variables
        env:
          step_variable: "!"
        run: |
          echo "hi ${{vars.USER}}"
          echo "listen the truth from me ${{secrets.TRUTH}}"
          echo "repository name is ${{github.repository}}"
          echo "$global_variable $job_variable $step_variable"

      - name: Deploy
        run:  python main.py
        

